### ISSUE TITLE
forEachView{...} extension and more...

### ISSUE THREAD

**Issue by IODevBlue** [vladleesi/kutilicious#4]
Great library! I came across your library on reddit and I thought I'd add a few suggestions.

There should be a extension to execute a lambda on a `View` object.

The lambda should recursively execute a particular function on a given `View` object and it's children `View` objects if it is a ViewGroup.

```kotlin
/** Something like this. */
fun View.forEachView(exec:()->Unit) {
     if (this is ViewGroup) { //recursively execute exec() }
     else if (this is View) { exec() }
}
``` 

Also you can create Integer extensions for Android colors.

The ColorUtils class doesn't really have much utility functions.

For example..an Integer extension to lighten up an android Integer color by a certain percentage.

Like so:

```kotlin
fun Int.lightenColor(@FloatRange(from=0.0, to=1.0) by: float): Int {//perfom lightening operations.}
``` 

Here's one from ChatGPT to give an idea:

```kotlin
/**
 * Lightens a given Android color int by a specified percentage.
 *
 * @param colorInt The Android color int to be lightened.
 * @param percentage The percentage by which to lighten the color. It should be a float value between 0 and 1.
 *                   A value of 0 will result in no change, while a value of 1 will make the color fully white.
 * @return The lightened Android color int.
 */
fun lightenColor(colorInt: Int, percentage: Float): Int {
    // Extract the ARGB components of the color
    val alpha = Color.alpha(colorInt)
    val red = Color.red(colorInt)
    val green = Color.green(colorInt)
    val blue = Color.blue(colorInt)

    // Calculate the lightened RGB values
    val lightenedRed = (red + (255 - red) * percentage).toInt()
    val lightenedGreen = (green + (255 - green) * percentage).toInt()
    val lightenedBlue = (blue + (255 - blue) * percentage).toInt()

    // Create the lightened color by combining the ARGB values
    return Color.argb(alpha, lightenedRed, lightenedGreen, lightenedBlue)
}
```

This Javadoc provides a clear and concise explanation of the function, including the purpose of the function, the parameters it takes, and the expected behavior. It also specifies the valid range for the `percentage` parameter and clarifies that a value of 0 results in no change, while a value of 1 makes the color fully white.

**Comment by vladleesi** [comment]
@IODevBlue, thanks a lot for your suggestions!
I'll incorporate them in the next version update, or if you're interested, you can implement them yourself. 
Your input is highly appreciated!

**Comment by vladleesi** [comment]
@IODevBlue It's done! Added to [0.8.1](https://github.com/vladleesi/kutilicious/releases/tag/0.8.1), thanks for your suggestions.

**Comment by jdvp** [comment]
For reference, the algorithm chat gpt gave is a simple linear interpolation of Color X and White. 

Not an issue with it as implemented as far as I can tell but just wanted to mention it. If you happen to use compose in your project, you can do the same thing with

```
    @ColorInt
    private fun @receiver:ColorInt Int.lighten(
        percentage: Float
    ): Int {
        return lerp(Color(this), Color.White, percentage).toArgb()
    }
```

Although if using compose, you could argue that they should just directly use the compose colors. 

Regardless, `lerp` is great since you can also use it to darken colors (if you provide Color.Black as the second color) or just to blend colors in general. AFAIK lerp never made it's way to the main android.graphics APIs but it did make it to one of the support libs

Anyway, just mentioning since something chatgpt will just recommend things without really mentioning what they are (the color lerp function in this case)

**Comment by vladleesi** [comment]
@jdvp Thank you for bringing this to my attention, I wasn't aware of it before.
It's really nice to use ready tools, but unfortunately, it only works in the compose package.

**Comment by jdvp** [comment]
Yep, makes sense. Android own implementation seems to have ended up in an androidx lib as a function called [`blendARGB`](https://developer.android.com/reference/kotlin/androidx/core/graphics/ColorUtils#blendARGB(int,int,float)). A little surprised by that because lots of languages include lerp/blend in their base color utilities so it's strange that android hadn't

anyway, thanks for adding it to your lib

**Comment by vladleesi** [comment]
@jdvp Perfect! 
`Color.BLUE.lightenColor(percent)` and `ColorUtils.blendARGB(Color.BLUE, Color.WHITE, percent)` have the same result.

![Screenshot_1690610957](https://github.com/vladleesi/kutilicious/assets/30999008/e6c41b47-86cf-4e05-8f41-27619a9835f8)

Thank you for pointing that out! I'll make sure to replace it with the standard method.

**Comment by vladleesi** [comment]
@jdvp Check it out in [0.8.2](https://github.com/vladleesi/kutilicious/releases/tag/0.8.2)
